### ISSUE TITLE
Concurrency: multiple swaps in progress in several browser tabs can make swaps disappear

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-web-app#498]
To reproduce open
Tab A
Tab B

Create a swap on tab A first.

Then create a swap on tab B.

Then pay tab B.
Then pay tab A.

Tab A will suddenly after a little bit refresh automatically to: 
Swap: 8BECEncszXXX
Swap not found!

```
index-762f6f80.js:244 Uncaught TypeError: Cannot read properties of null (reading 'asset')
    at Object.fn (index-762f6f80.js:244:12863)
    at ST (index-762f6f80.js:1:4303)
    at Rh (index-762f6f80.js:1:4244)
    at sC (index-762f6f80.js:1:5026)
    at MT (index-762f6f80.js:1:5487)
    at index-762f6f80.js:1:5326
    at Ig (index-762f6f80.js:1:5186)
    at kT (index-762f6f80.js:1:5319)
    at Ig (index-762f6f80.js:1:5197)
    at P0 (index-762f6f80.js:1:1865)
```

Looks like everything uses the same storage key.

**Comment by dni** [comment]
cannot reproduce

**Comment by LordDotSH** [comment]
Was it exact with two different tabs in same browser, you started the order on both, but pay on your last created order first, then the first order, with them still both open/not refreshed manually?

If it doesn't work I'm cool to try reproduce it again and then do a screenshare with you.
